/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmailSignatureRouteImport } from './routes/email-signature'

const EmailSignatureRoute = EmailSignatureRouteImport.update({
  id: '/email-signature',
  path: '/email-signature',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/email-signature': typeof EmailSignatureRoute
}
export interface FileRoutesByTo {
  '/email-signature': typeof EmailSignatureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/email-signature': typeof EmailSignatureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/email-signature'
  fileRoutesByTo: FileRoutesByTo
  to: '/email-signature'
  id: '__root__' | '/email-signature'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EmailSignatureRoute: typeof EmailSignatureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/email-signature': {
      id: '/email-signature'
      path: '/email-signature'
      fullPath: '/email-signature'
      preLoaderRoute: typeof EmailSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EmailSignatureRoute: EmailSignatureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
